#!/bin/zsh
set -e

# Set up Prezto
mkdir -p ~/.zprezto
cd ~/.zprezto
if [ -d .git ]; then
  git pull
else
  git clone --recursive https://github.com/sorin-ionescu/prezto.git ~/.zprezto
fi

setopt EXTENDED_GLOB
for rcfile in ~/.zprezto/runcoms/^README.md(.N); do
  ln -fsn "$rcfile" ~/.${rcfile:t}
done
#shell expansion "~" can't be in quotes, we use "" for security

# Symlink dot/* into home directory as hidden files
for f in $(ls -d ~/.dotfiles/dot/*); do ln -sfn $f ~/.$(basename $f); done

# Symlink files/* into home directory as regular files
for f in $(ls -d ~/.dotfiles/files/*); do ln -sfn $f ~/$(basename $f); done

echo "such successfulness"
